services:
    redis:
        container_name: "somebackgroundservice_redis"
        ports:
            - "6379:6379"

    rabbit_cluster_1:
        container_name: "rabbit_cluster_1"
        hostname: "rabbit_cluster_1"
        environment:
            RABBITMQ_ERLANG_COOKIE: "supersecretcookie"
        ports:
            - "5675:5672"
            - "15675:15672"

    rabbit_cluster_2:
        container_name: "rabbit_cluster_2"
        hostname: "rabbit_cluster_2"
        environment:
            RABBITMQ_ERLANG_COOKIE: "supersecretcookie"

    weather_service:
        container_name: "weather_service"
        ports:
            - "5000:8080"
        depends_on:
            - redis
            - rabbit_cluster_1
            - rabbit_cluster_2



