services:
    redis:
        image: redis

    rabbit_cluster_1: 
        image: rabbitmq:4.2-management 
    
    rabbit_cluster_2: 
        image: rabbitmq:4.2-management

    weather_service:
        build: ./WeatherForecastAPI

    yarpapigateway:
        image: ${DOCKER_REGISTRY-}yarpapigateway
        build:
          context: ReverseProxy/YarpApiGateway
          dockerfile: Dockerfile

