services:
    redis:
        container_name: "somebackgroundservice_redis"
        ports:
            - "6379:6379"

    rabbit_cluster_1:
        container_name: "rabbit_cluster_1"
        hostname: "rabbit_cluster_1"
        environment:
            RABBITMQ_ERLANG_COOKIE: "supersecretcookie"
        ports:
            - "5675:5672"
            - "15675:15672"

    rabbit_cluster_2:
        container_name: "rabbit_cluster_2"
        hostname: "rabbit_cluster_2"
        environment:
            RABBITMQ_ERLANG_COOKIE: "supersecretcookie"



